name: yt_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.1.0
  youtube_explode_dart: ^1.12.0
  animated_background: ^2.0.0

  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  cloud_firestore: ^3.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
